# Generated by Django 4.1.5 on 2023-02-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='DateOfBirth',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
