# Generated by Django 4.1.5 on 2023-02-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customermodel_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='DateOfBirth',
            field=models.DateField(error_messages={'invalid': 'Enter in this YYYY-MM-DD'}, verbose_name='DateOfBirth YYYY-MM-DD'),
        ),
    ]
