# Generated by Django 4.1.5 on 2023-02-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customermodel_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='DateOfBirth',
            field=models.DateField(default='1990-12-26', error_messages={'invalid_date': 'Enter in this YYYY-MM-DD'}, verbose_name='DateOfBirth YYYY-MM-DD'),
        ),
    ]
